<!-- application/views/scripts/index/index.phtml -->
<div class="wrapper">
	<div id="slides">
		<img src="images/slideshow/1.png">
		<img src="images/slideshow/2.png">
		<img src="images/slideshow/3.png">
		<img src="images/slideshow/4.png">
		<img src="images/slideshow/5.png">
	</div><!--slides-->
	<div class="news">
		<h2>New Releases</h2>
		 <div id="tabsholder">
			<ul class="tabs">
				<li id="tab2">Women</li>
				<li id="tab1">Men</li>
				<li id="tab3">Kids</li>
			</ul>
			<div class="contents marginbot">
				<div id="content1" class="tabscontent"></div><!--content1-->
				<div id="content2" class="tabscontent">
					<div class="frame-1">
						<canvas id="box-1" width="300" height="128"></canvas>
						<p class="text-box">Lorem ipsum dolor.</p>
						<canvas id="box-2" width="300" height="124"></canvas>		
					</div><!--frame-1-->
					<div class="frame-2">
						<canvas id="box-3" width="290" height="204"></canvas>
						<p class="text-box">Dolor sit amet</p>
						<canvas id="box-4" width="290" height="49"></canvas>	
					</div><!--frame-2-->
					<div class="frame-3">
						<canvas id="box-5" width="297" height="46"></canvas>
						<p class="text-box">Sadipicing elit</p>
						<canvas id="box-6" width="297" height="207"></canvas>
					</div><!--frame-3-->
				</div><!--content2-->
				<div id="content3" class="tabscontent"></div><!--content3-->
			</div><!--contents marginbot-->
		</div><!--tabsholder-->
	</div><!--news-->
	<div id="content">
		<h2>Lorem Ipsum Dolor</h2>
		<article>
		<div id="column-1">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at libero sed diam ullamcorper ornare. Morbi adipiscing quam quis quam facilisis sed faucibus urna vehicula. Vestibulum malesuada justo nec tortor commodo bibendum. Nulla at urna sed est cursus consectetur ut ut lacus. Nunc ornare tempus quam, ullamcorper tempor ante sagittis sit amet. Sed nisl velit, commodo ac interdum quis, luctus sed lorem. In hac habitasse platea dictumst. Morbi urna dui, iaculis ac tempus eu, tempor ac dui. Nunc in diam arcu. Nulla est libero, facilisis a pharetra non, facilisis a orci. Phasellus tempor vestibulum neque, sit amet </p>
		</div><!--column-1-->
		<div id="column-2">
		<p>Sed pretium porta elit, eget consectetur ante fringilla vitae. Aliquam erat volutpat. Nam ut mattis lacus. Sed et tellus in nulla mattis feugiat. Nulla aliquet neque non urna iaculis vel aliquam risus iaculis. Mauris eget velit a velit porttitor adipiscing. Pellentesque habitant morbi tristique senectus et netus et. Morbi adipiscing quam quis quam facilisis sed faucibus urna vehicula. Vestibulum malesuada justo nec tortor commodo bibendum. Nulla at urna sed est cursus consectetur ut ut lacus.</p>
		</div><!--column-2-->
		</article>
	</div><!--content-->
<div class="empty"></div><!--empty-->
</div><!--wrapper-->

