<!-- application/views/scripts/footer.phtml-->
<div class="footer-wrap">
<div class ="footer">
	<div id="footer-left">
		<h1>Follow</h1></br>
		<a href="#"><img src="images/facebook.png"></a><span class="footer-data">Facebook</span></br></br>
		<a href="#"><img src="images/twitter.png"></a><span class="footer-data">Twitter</span>
	</div><!--footer-left-->
	<div id="footer-center">
		<h1>Contact</h1></br>
		<span class="contact">
		<p>Company name
		730 Fifth Avenue 9th Floor
		New York, NY 10019
		USA<p></span>
	</div><!--footer-center-->
	<div id="footer-right">
		<div class="subscribe">
			<h1>Subscribe</h1></br>
			<div class="sub-wrapper">
				<form action="#" method="post" class="sub-email">
				<input class="area" type="text" name="mail" placeholder="first.lastname@example.com">
				<input class="submit" type="submit" value="Submit">
				</form>
				<div id="error"></div>
					<div id="test"></div>
			</div><!--sub-wrapper-->
		</div><!--subscribe-->
	</div><!--footer-right-->
	<div class="divider"><p>&copy copyright 2012, all rights reserved</p></div><!--divider-->	
</div><!--footer-->
</div><!--footer-wrap-->